_____public_python/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

contacts/urls.py
from django.conf.urls import url


from .views import (
    ContactsListView,
    ContactsDetailView,
    AjaxContactCreateView,
    AjaxContactUpdateView
)

urlpatterns = [
    url(r'^create/$', AjaxContactCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[\w-]+)/update/$', AjaxContactUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>[\w-]+)/$', ContactsDetailView.as_view(), name='detail'),
    url(r'$', ContactsListView.as_view(), name='list')
]

crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth.views import (
    LoginView, 
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.core.urlresolvers import reverse_lazy

from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', LoginView.as_view(template_name='user/login.html', redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
     url(r'^password_reset/done/$',
        PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^reset/done/$',
        PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
    url(r'^clients/', include('clients.urls', namespace='clients')), 
    url(r'^products/', include('products.urls', namespace='products')), 
    url(r'^agreements/', include('agreements.urls', namespace='agreements')), 
    url(r'^transactions/', include('transactions.urls', namespace='transactions')),
    url(r'^commisions/', include('commisions.urls', namespace='commisions')),
    url(r'^employees/', include('employees.urls', namespace='employees')),  
    url(r'^events/', include('events.urls', namespace='events')),  
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),  
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),  
    url(r'^$', login_required(TemplateView.as_view(template_name='index.html')), name='about'),
]

contacts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

User = settings.AUTH_USER_MODEL

# Create your models here.
class Contact(models.Model):
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=50)
    email = models.CharField(max_length=30, blank = True, null = True)
    tel = models.CharField(max_length=30, blank = True, null = True)
    is_appointed = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('contacts:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name + ' ' + self.surname

contacts/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from crm.shortcuts.shortcuts import get_object_or_json404

from crm.mixins.ajaxformresponse import AjaxFormResponseMixin

from .models import Contact

class ContactsListView(LoginRequiredMixin, ListView):
    def get_queryset(self, *args, **kwargs):
        return Contact.objects.all()


class ContactsDetailView(LoginRequiredMixin, DetailView):
    def get_queryset(self, *args, **kwargs):
        return Contact.objects.all()
        


class AjaxContactCreateView(LoginRequiredMixin, AjaxFormResponseMixin, CreateView):
    model = Contact
    fields = ('name', 'surname', 'email', 'tel')

    def get_object(self, queryset=None):
        return get_object_or_json404(Contact, pk=self.kwargs['pk'])

    def get_context_data(self, context):
        context['success'] = True
        return context
    def form_valid(self, form):
        contact = form.save(commit=False)
        contact.owner = self.request.user
        contact.save()
        return super(AjaxContactCreateView, self).form_valid(form)

class AjaxContactUpdateView(LoginRequiredMixin, AjaxFormResponseMixin, UpdateView):
    model = Contact
    fields = ('is_appointed',)

    def get_object(self, queryset=None):
        return get_object_or_json404(Contact, pk=self.kwargs['pk'])

    def get_context_data(self, context):
        context['success'] = True
        return context

    # def form_valid(self, form):
    #     contact = form.save(commit=False)
    #     contact.is_appointed = True
    #     contact.owner = self.request.user
    #     contact.save()
    #     return super(AjaxContactUpdateView, self).form_valid(form)

contacts/templates/contacts/contact_detail.html
{% extends "base_site.html" %}
{% load myfilters %}

{% block title %} Profile {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_content">
              <div class="col-md-6 col-sm-6 col-xs-12 profile_left">

                <h1>{{object.name}} {{object.surname}} </h1>
                
                <ul class="list-unstyled user_data">
                <br>
                <h4>Dane kontaktowe</h4>
                <ul class="list-unstyled user_data">
                    <li>
                       <a href="mailto:{{object.email}}"><i class="fa fa-envelope-o"></i> {{object.email}}</a>
                    </li>
                    <li>
                        <a href="tel:{{object.tel}}"><i class="fa fa-phone"></i> {{object.tel}}</a>
                    </li>

                </ul>
                <br>

                <p>Uwtorzony:
                    <small style="color:#73879C; padding:3px 6px; background: none; border: 1px solid #73879C; margin: 5px auto">{{object.timestamp|timesince}} temu</small></p>
                
                <p>Ostatnio edytowany:
                  <small style="color:#73879C; padding:3px 6px; background: none; border: 1px solid #73879C;  ">{{object.updated|timesince}} temu</small>
                </p><br>

                <a class="btn btn-success" href=""><i class="fa fa-edit m-right-xs"></i> Edytuj</a>
                <a class="btn btn-default" href="{% url 'contacts:list' %}"><i class="fa fa-list m-right-xs"></i> Lista kontaktów</a>
                <br />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}

{% endblock javascripts %} 

contacts/templates/contacts/contact_list.html
{% extends "base_site.html" %}

{% block title %} Table Dynamic {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Kontakty</h3>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel"><br>
              <a href="{% url 'clients:create' %}" class="btn btn-primary" role="button"><i class="fa fa-plus-square-o" aria-hidden="true"></i> Dodaj kontakt</a><br><br>

              <div class="x_content">
                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                  <thead>
                    <tr>
                      <th>Imię</th>
                      <th>Nazwisko</th>
                      <th>E-mail</th>
                      <th>Numer telefonu</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for contact in object_list %}
                    <tr>
                      <td>{{contact.name}}</td>
                      <td>{{contact.surname}}</td>
                      <td>{{contact.email}}</td>
                      <td>{{contact.tel}}</td>
                      <td ><a style="font-size: 0.8em;" href="{{ contact.get_absolute_url }}" class="btn btn-info" role="button"><i class="fa fa-search" aria-hidden="true"></i></a></td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
      
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- Datatables -->
  <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
  <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
  <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
  <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
{% endblock javascripts %}