_____public_python/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

clients/urls.py
from django.conf.urls import url


from .views import (
    ClientsListView,
    ClientsListAllView,
    ClientCreateView,
    ClientDetailView,
    ClientUpdateView
)

urlpatterns = [
    url(r'^create/$', ClientCreateView.as_view(), name='create'),
    url(r'^all/$', ClientsListAllView.as_view(), name='list-all'),
    url(r'^(?P<slug>[\w-]+)/$', ClientDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', ClientUpdateView.as_view(), name='edit'),
    url(r'$', ClientsListView.as_view(), name='list')
]

crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth.views import (
    LoginView, 
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.core.urlresolvers import reverse_lazy

from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', LoginView.as_view(template_name='user/login.html', redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
     url(r'^password_reset/done/$',
        PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^reset/done/$',
        PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
    url(r'^clients/', include('clients.urls', namespace='clients')), 
    url(r'^products/', include('products.urls', namespace='products')), 
    url(r'^agreements/', include('agreements.urls', namespace='agreements')), 
    url(r'^transactions/', include('transactions.urls', namespace='transactions')),
    url(r'^commisions/', include('commisions.urls', namespace='commisions')),
    url(r'^employees/', include('employees.urls', namespace='employees')),  
    url(r'^events/', include('events.urls', namespace='events')),  
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),  
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),  
    url(r'^$', login_required(TemplateView.as_view(template_name='index.html')), name='about'),
]

events/urls.py
from django.conf.urls import url

from .views import (
    EventListView,
    EventListAllView,
    AjaxEventCreateView,
    AjaxEventUpdateView,
    AjaxEventDeleteView
)

urlpatterns = [
    url(r'^create/$', AjaxEventCreateView.as_view(), name='create'),
    url(r'^all/$', EventListAllView.as_view(), name='list-all'),
    url(r'^(?P<id>[\w-]+)/edit/$', AjaxEventUpdateView.as_view(), name='edit'),
    url(r'^(?P<id>[\w-]+)/delete/$', AjaxEventDeleteView.as_view(), name='delete'),
    url(r'$', EventListView.as_view(), name='list') 
]

templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

templates/snippets/footer.html
<div class="pull-right">
  DAHARODS Selected Solutions
</div>
<div class="clearfix"></div>

templates/snippets/form-snippet.html
{% if form.errors %}
{{ form.errors }}
{% endif %}
<form method='POST'> {% csrf_token %}
    {{ form.as_p }}
    {{ form.branch }}
    <button type='submit'>Save</button>
</form>

templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

templates/snippets/nav.html
<div class="container">
    <h1>CRM</h1>
    <ul>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'clients:list' %}">Clients</a></li>
    </ul>
</div>

templates/snippets/sidebar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="../" class="site_title"><img src="/static/images/logo.png" alt="" style="width: 80%; margin: 0 15px;"></a>
  </div>

  <div class="clearfix"></div>

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <h3>Menu</h3>
      <ul class="nav side-menu">

        <li><a><i class="fa fa-user"></i> Transakcje <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            {% if user.is_authenticated and user.employee.role == 'A' %}
            <li><a href="{% url 'transactions:list-all' %}">Wszystkie transakcje</a></li>
            {% endif %}           
            <li><a href="{% url 'transactions:list' %}">Moje transakcje</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-user"></i> Klienci <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'clients:create' %}">Dodaj klienta</a></li>
            <li><a href="{% url 'clients:list' %}">Moi klienci</a></li>
            {% if user.is_authenticated and user.employee.role == 'A' %}
            <li><a href="{% url 'clients:list-all' %}">Wszyscy klienci</a></li>
            {% endif %} 
          </ul>
        </li>
        <li><a><i class="fa fa-file-o"></i> Umowy <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'agreements:create' %}">Dodaj umowę</a></li>
            <li><a href="{% url 'agreements:list' %}">Moje umowy</a></li>
            {% if user.is_authenticated and user.employee.role == 'A' %}
            <li><a href="{% url 'agreements:list-all' %}">Wszystkie umowy</a></li>
            {% endif %} 
          </ul>
        </li>
        <li><a><i class="fa fa-th-large"></i> Produkty <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            {% if user.is_authenticated and user.employee.role == 'A' %}
              <li><a href="{% url 'products:create' %}">Dodaj produkt</a></li>
            {% endif %}
            <li><a href="{% url 'products:list' %}">Pokaz produkty</a></li>
          </ul>
        </li>
        {% if user.is_authenticated and user.employee.role == 'A' %}
        <li><a><i class="fa fa fa-users"></i> Pracownicy <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'employees:create' %}">Dodaj pracownika</a></li>
            <li><a href="{% url 'employees:list' %}">Pokaz pracowników</a></li>
          </ul>
        </li>
        {% endif %}
        <li><a><i class="fa fa-calendar"></i> Kalendarz <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'events:list' %}">Pokaż mój kalendarz</a></li>
            {% if user.is_authenticated and user.employee.role == 'A' %}
              <li><a href="{% url 'events:list-all' %}">Pokaż ogólny kalendarz</a></li>
            {% endif %}
          </ul>
        </li>
        <li><a href="{% url 'notifications:list' %}"><i class="fa fa-bell"></i> Powiadomienia </a>
        </li>
      </ul>
    </div>
  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->

  <!-- /menu footer buttons -->
</div>

templates/snippets/top_navigation.html
<div class="nav_menu">
  <nav>
    <div class="nav toggle">
      <a id="menu_toggle"><i class="fa fa-bars"></i></a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li class="">
        <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          {% if user.is_authenticated %}
            {{ request.user.employee.name }} {{ request.user.employee.surname }}
          {% else %}
              Niezalogowany
          {% endif %}
          <span class=" fa fa-angle-down"></span>
        </a>
        <ul class="dropdown-menu dropdown-usermenu pull-right">
          {% if user.is_authenticated %}
          <li><a href="{% url 'employees:detail' user.username %}"> Moje ustawienia</a></li>
          <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out pull-right"></i> Wyloguj</a></li>
          {% endif %}
        </ul>
      </li>

      <li role="presentation" class="dropdown">
        <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
          <i class="fa fa-envelope-o"></i>
          <span class="badge bg-green notifications_counter">{{notifications_unread}}</span>
        </a>
        <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            {% for notification in  notifications|dictsortreversed:"timestamp"|slice:":5" %}
                <li>
                  <a href="{{notification.content_object.get_absolute_url}}">
                    <span class="image"><i class="fa fa-info-circle" aria-hidden="true"></i> </span>
                      <span> {{notification.content_object.name}} {{notification.content_object.surname}}</span>
                      <span class="time">{{ notification.timestamp|timesince }} temu</span>
                    </span>
                    <span class="message">
                      {{ notification.content }}
                    </span>
                  </a>
                </li>
              {% empty %}
              <li><p class="text-center">Brak nowych powiadomień</p></li>
            {% endfor %}
          <li>
            <div class="text-center">
              <a>
                <strong>Zobacz wszystkie powiadomienia</strong>
                <i class="fa fa-angle-right"></i>
              </a>
            </div>
          </li>
        </ul>
      </li>
    </ul>
    
  </nav>
</div>