_____public_python/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

clients/urls.py
from django.conf.urls import url


from .views import (
    ClientsListView,
    ClientsListAllView,
    ClientCreateView,
    ClientDetailView,
    ClientUpdateView
)

urlpatterns = [
    url(r'^create/$', ClientCreateView.as_view(), name='create'),
    url(r'^all/$', ClientsListAllView.as_view(), name='list-all'),
    url(r'^(?P<slug>[\w-]+)/$', ClientDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', ClientUpdateView.as_view(), name='edit'),
    url(r'$', ClientsListView.as_view(), name='list')
]

crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth.views import (
    LoginView, 
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.core.urlresolvers import reverse_lazy

from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', LoginView.as_view(template_name='user/login.html', redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
     url(r'^password_reset/done/$',
        PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^reset/done/$',
        PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
    url(r'^clients/', include('clients.urls', namespace='clients')), 
    url(r'^products/', include('products.urls', namespace='products')), 
    url(r'^agreements/', include('agreements.urls', namespace='agreements')), 
    url(r'^transactions/', include('transactions.urls', namespace='transactions')),
    url(r'^commisions/', include('commisions.urls', namespace='commisions')),
    url(r'^employees/', include('employees.urls', namespace='employees')),  
    url(r'^events/', include('events.urls', namespace='events')),  
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),  
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),  
    url(r'^$', login_required(TemplateView.as_view(template_name='index.html')), name='about'),
]

clients/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save
from django.core.urlresolvers import reverse
from django_countries.fields import CountryField
from datetime import datetime
from django.contrib.contenttypes.fields import GenericRelation

from crm.utils import unique_slug_generator, client_id_generator

User = settings.AUTH_USER_MODEL


class Client(models.Model):
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=30)
    second_name = models.CharField(max_length=30, blank=True)
    surname = models.CharField(max_length=50)
    birthday = models.DateField(auto_now=False, auto_now_add=False, default=datetime.now().strftime("%Y-%m-%d"))
    gender = models.CharField(max_length=1)
    city = models.CharField(max_length=100)
    pesel = models.DecimalField(max_digits=11, decimal_places=0)
    client_id = models.CharField(max_length=20, blank = True, null = True)
    client_state = models.CharField(max_length=1)
    doc_type = models.CharField(max_length=1)
    doc_nr = models.CharField(max_length=30)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank = True, null = True)
    notification = GenericRelation('notifications.Notification', related_query_name="clients")

    def __str__(self):
        return self.name + ' ' + self.surname + ' (' + self.client_id + ')' 

    def get_absolute_url(self):
        return reverse('clients:detail', kwargs={'slug': self.slug})


class ClientContactData(models.Model):
    EMAIL = 'E'
    TELEPHONE = 'T'
    TAG_CHOICES = (
        (EMAIL, 'E-mail'),
        (TELEPHONE, 'Numer telefonu')
    )
    client_id = models.ForeignKey(Client)
    contact_type = models.CharField(max_length=1, choices=TAG_CHOICES, default=EMAIL)
    value = models.CharField(max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class ClientAddress(models.Model):
    REGISTERED = 'R'
    RESIDENCE = 'A'
    CONTACT = 'C'
    TAG_CHOICES = (
        (REGISTERED, 'Adres zameldowania'),
        (RESIDENCE, 'Adres zamieszkania'),
        (CONTACT, 'Adres kontaktowy')
    )
    client_id = models.ForeignKey(Client)
    contact_type = models.CharField(max_length=1, choices=TAG_CHOICES, default=REGISTERED)
    street = models.CharField(max_length=40)
    house_nr = models.CharField(max_length=20)
    apartment_nr = models.CharField(max_length=20)
    post = models.CharField(max_length=40)
    postal_code = models.CharField(max_length=6)
    country = CountryField()
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.street

def client_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
    if not instance.client_id:
        client_id = client_id_generator(instance)
        if Client.objects.filter(client_id=client_id).exists():
            print(Client.objects.filter(client_id=client_id).exists())
            instance.client_id = client_id_generator(instance)
        else:
            instance.client_id = client_id

pre_save.connect(client_pre_save_receiver, sender=Client)

clients/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from django.forms.models import inlineformset_factory, modelformset_factory
from .models import Client, ClientAddress, ClientContactData
from django_countries.fields import LazyTypedChoiceField
from django_countries.widgets import CountrySelectWidget
from crm.settings.base import DATE_INPUT_FORMATS

class ClientCreateForm(forms.ModelForm):
    GENDERS = [('K','Kobieta'), ('M','Mężczyzna')]
    STATES = [('A','Aktywny'), ('U','Zarchiwizowany')]
    DOC_TYPE = [('D','Dowód osobisty'), ('P','Paszport'), ('I','Inny')]
    gender = forms.ChoiceField(choices=GENDERS,widget=forms.RadioSelect())
    client_state = forms.ChoiceField(choices=STATES,widget=forms.RadioSelect())
    doc_type = forms.ChoiceField(choices=DOC_TYPE,widget=forms.RadioSelect())
    birthday = forms.DateField(input_formats=DATE_INPUT_FORMATS)
    class Meta:
        model = Client
        exclude = ('owner','slug', 'client_id')


ClientFormSet = inlineformset_factory(Client, ClientAddress, extra=0, min_num=1, max_num=3, exclude=('gender','slug', 'client_id'))
ContactFormSet = inlineformset_factory(Client, ClientContactData, extra=0, min_num=1, max_num=10, exclude=('client_id',))

clients/views.py
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404, render_to_response, HttpResponseRedirect
from django.db import transaction
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, Max
from django.core.exceptions import PermissionDenied

from .models import Client, ClientAddress, ClientContactData
from .forms import ClientCreateForm, ClientFormSet, ContactFormSet
from transactions.models import Transaction
from agreements.models import Agreement


class ClientsListView(LoginRequiredMixin, ListView):
    def get_queryset(self, *args, **kwargs):
        return Client.objects.filter(owner=self.request.user)


class ClientsListAllView(LoginRequiredMixin, ListView):
    def get_queryset(self, *args, **kwargs):
        qs = Client.objects.all()
        return qs

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data(object_list=self.object_list)
        if self.request.user.employee.role is 'A':
            return self.render_to_response(context)
        else:
            raise PermissionDenied


class ClientDetailView(LoginRequiredMixin, DetailView):
    def get_queryset(self, *args, **kwargs):
        if self.request.user.employee.role == 'A':
            return Client.objects.all()
        return Client.objects.filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(ClientDetailView, self).get_context_data(**kwargs)
        client = Client.objects.get(slug__iexact=self.kwargs['slug'])
        context['total_amount'] = Transaction.objects.filter(client_id=client).aggregate(Sum('amount'))['amount__sum']
        context['total_fee'] = Transaction.objects.filter(client_id=client).aggregate(Sum('fee'))['fee__sum']
        context['max_amount'] = Transaction.objects.filter(client_id=client).aggregate(Max('amount'))['amount__max']
        return context
        

class ClientCreateView(LoginRequiredMixin, CreateView):
    template_name = 'clients/client_form.html'
    model = Client
    form_class = ClientCreateForm

    def get_context_data(self, *args, **kwargs):
        data = super(ClientCreateView, self).get_context_data(*args, **kwargs)
        data['title'] = 'Dodaj klienta'
        if self.request.POST:
            data['clientaddress'] = ClientFormSet(self.request.POST)
            data['clientcontact'] = ContactFormSet(self.request.POST)
        else:
            data['clientaddress'] = ClientFormSet()
            data['clientcontact'] = ContactFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        clientaddress = context['clientaddress']
        clientcontact = context['clientcontact']
        with transaction.atomic():
            client = form.save(commit=False)
            client.owner = self.request.user
            if form.has_changed():
                client.save()
            if clientaddress.is_valid() and form.is_valid() and clientcontact.is_valid():
                self.object = form.save()
                clientaddress.instance = self.object
                clientaddress.save()
                self.object = clientcontact.save(commit=False)
                for contact in self.object:
                    contact.client_id = client
                    contact.save()
        return super(ClientCreateView, self).form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientCreateForm
    template_name = 'clients/client_form.html'

    def get_context_data(self, *args, **kwargs):
        data = super(ClientUpdateView, self).get_context_data(*args, **kwargs)
        data['title'] = 'Edytuj dane klienta'
        if self.request.POST:
            data['clientaddress'] = ClientFormSet(self.request.POST, instance=self.object)
            data['clientcontact'] = ContactFormSet(self.request.POST, instance=self.object)
        else:
            data['clientaddress'] = ClientFormSet(instance=self.object)
            data['clientcontact'] = ContactFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        clientaddress = context['clientaddress']
        clientcontact = context['clientcontact']
        with transaction.atomic():
            client = form.save(commit=False)
            client.owner = self.request.user
            if form.has_changed():
                client.save()
            if clientaddress.is_valid() and form.is_valid() and clientcontact.is_valid():
                self.object = form.save()
                clientaddress.instance = self.object
                clientaddress.save()
                self.object = clientcontact.save(commit=False)
                for contact in self.object:
                    contact.client_id = client
                    contact.save()
                clientcontact.save()
        return super(ClientUpdateView, self).form_valid(form)

clients/templates/clients/client_detail.html
{% extends "base_site.html" %}
{% load myfilters %}

{% block title %} Profile {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_content">
              <div class="col-md-3 col-sm-3 col-xs-12 profile_left">

                <h1>{{object.name}} {{object.second_name}} {{object.surname}} </h1>
                
                <small style="color:#fff; padding:3px 6px; background: #73879C">{{object.client_id}}</small>
                <small style="color:#fff; padding:3px 6px; {% if object.client_state == 'A'%} background: #5cb85c {%  else %} background: #73879C {% endif %}">{{object.client_state|state}}</small> 
                <br><br>

                <ul class="list-unstyled user_data">
                  <li><i class="fa fa-map-marker user-profile-icon"></i> | {{object.city}}
                  </li>

                  <li>
                    <i class="fa fa-birthday-cake user-profile-icon"></i> | {{object.birthday}}
                  </li>

                  <li class="m-top-xs">
                    <b>PESEL</b> | {{object.pesel}}
                  </li>
                </ul>
                <br>
                <h4>Dokument tożsamości</h4>
                <ul class="list-unstyled user_data">
                  <li><i class="fa fa-id-card user-profile-icon"></i> | {{object.doc_type|doc_type}}
                  </li>

                  <li class="m-top-xs">
                    <b>NUMER</b> | {{object.doc_nr}}
                  </li>
                  
                </ul>
                <br>
                <h4>Adresy</h4>
                <ul class="list-unstyled user_data">
                  {% for address in object.clientaddress_set.all %}
                    <li><i class="fa fa-home" aria-hidden="true"></i> | <b>{{address.contact_type|address_type}}</b>
                      <p>
                        {{address.street}} {{address.house_nr}}/{{address.apartment_nr}} <br>
                        {{address.postal_code}} {{address.post}}, {{address.country}}         
                      </p>
                    </li>
                    {% empty %}
                      Brak wyników
                  {% endfor %}
                </ul>
                <br>
                <h4>Dane kontaktowe</h4>
                <ul class="list-unstyled user_data">
                  {% for contact in object.clientcontactdata_set.all %}
                    <li><i class="fa fa-home" aria-hidden="true"></i> | <b>{{contact.contact_type|contact_type}}</b>
                      <p>
                       <a href="{% if contact.contact_type == 'E' %}mailto:{{contact.value}}{% elif contact.contact_type == 'T' %}tel:{{contact.value}}{% endif %}">{{contact.value}}</a>
                      </p>
                    </li>
                    {% empty %}
                      Brak wyników
                  {% endfor %}
                </ul>
                <br>

                <p>Uwtorzony:
                    <small style="color:#73879C; padding:3px 6px; background: none; border: 1px solid #73879C; margin: 5px auto">{{object.timestamp|timesince}} temu</small></p>
                
                <p>Ostatnio edytowany:
                  <small style="color:#73879C; padding:3px 6px; background: none; border: 1px solid #73879C;  ">{{object.updated|timesince}} temu</small>
                </p>
                
                <p>Uwtorzony przez:
                    <small style="color:#73879C; padding:3px 6px; background: none; border: 1px solid #73879C; margin: 5px auto">{{object.owner.employee}}</small></p>
                <br>

                <a class="btn btn-success" href="{% url 'clients:edit' object.slug %}"><i class="fa fa-edit m-right-xs"></i> Edytuj</a>
                <a class="btn btn-default" href="{% url 'clients:list' %}"><i class="fa fa-list m-right-xs"></i> Lista klientów</a>
                <br />

              </div>
              
              <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="row tile_count">
                  <div class="tile_stats_count">
                    <span class="count_top"><i class="fa fa-file-text-o"></i> Umowy</span>
                    <div class="count">{{object.transaction_set.all|length}}</div>
                  </div>
                  <div class="tile_stats_count">
                    <span class="count_top"><i class="fa fa-money"></i> Łącznie wpłacono</span>
                    <div class="count">{{total_amount|is_none}} </div>
                  </div>
                  <div class="tile_stats_count">
                    <span class="count_top"><i class="fa fa-money"></i> Łącznie prowizje</span>
                    <div class="count">{{total_fee|is_none}}</div>
                  </div>
                  <div class="tile_stats_count">
                    <span class="count_top"><i class="fa fa-money"></i> Najwyższa wpłata</span>
                    <div class="count">{{max_amount|is_none}}</div>
                  </div>
                  {% for notif in object.notification_set.all %}
                    {{notif}}
                  {% endfor %}

  
                </div>
                <div class="row agreements">
                  <h4>Aktywne umowy</h4>
                  <div class="ln_solid"></div>
                  <ul class="list-unstyled user_data">

                    {% for transaction in object.transaction_set.all %}
                      <li>
                        <p>
                            <span style="color:#fff; padding:3px 6px; background: #337ab7; margin: 5px auto">{{transaction.product_id}}</span></p><br>
                        <div class="progress progress_sm">
                          <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="{{transaction.time_left}}"></div><span> Pozostało: {{transaction.valid_to|timeuntil}}</span>
                        </div>
                        <p> Kwota:
                            <span style="color:#73879C; padding:3px 6px; background: none; border: 1px solid #73879C; margin: 5px auto">{{transaction.amount}} zł</span></p>

                        <p> Prowizja: 
                            <span style="color:#73879C; padding:3px 6px; background: none; border: 1px solid #73879C; margin: 5px auto">{{transaction.fee}} zł</span></p>

                        <p> Utworzono: 
                            <span style="color:#73879C; padding:3px 6px; background: none; border: 1px solid #73879C; margin: 5px auto">{{transaction.timestamp}}</span></p>

                            {% if user.is_authenticated %}
                            <p> Pracownik: 
                                <span style="color:#73879C; padding:3px 6px; background: none; border: 1px solid #73879C; margin: 5px auto">{{transaction.owner}}</span></p>
                            {% endif %}
                      </li>
                      {% empty %}
                      Brak wyników
                    {% endfor %}
                    
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}

{% endblock javascripts %} 

clients/templates/clients/client_list.html
{% extends "base_site.html" %}

{% block title %} Table Dynamic {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Klienci</h3>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel"><br>
              <a href="{% url 'clients:create' %}" class="btn btn-primary" role="button"><i class="fa fa-plus-square-o" aria-hidden="true"></i> Dodaj klienta</a><br><br>

              <div class="x_content">
                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Imię</th>
                      <th>Nazwisko</th>
                      <th>Miasto</th>
                      <th>PESEL</th>
                      <th>Status</th>
                      <th>Data utworzenia</th>
                      <th>Dodany przez</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for client in object_list %}
                    <tr>
                      <td>{{client.client_id}}</td>
                      <td>{{client.name}} {% if client.second_name %} ({{client.second_name}}) {% endif %}</td>
                      <td>{{client.surname}}</td>
                      <td>{{client.city}}</td>
                      <td>{{client.pesel}}</td>
                      <td>{{client.client_state}}</td>
                      <td>{{client.timestamp}}</td>
                      <td><a href="{% url 'employees:list' %}{{client.owner.username}}/">{{client.owner.username}}</a></a></td>
                      <td ><a style="font-size: 0.8em;" href="{{ client.get_absolute_url }}" class="btn btn-info" role="button"><i class="fa fa-search" aria-hidden="true"></i></a></td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
      
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- Datatables -->
  <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
  <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
  <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
  <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
  <script src="/static/vendors/jszip/dist/jszip.min.js"></script>
  <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script>
  <script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script>
{% endblock javascripts %}