_____public_python/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

agreements/urls.py
from django.conf.urls import url


from .views import (
    AgreementCreateView,
    AgreementDetailView,
    AgreementListView,
    AgreementListAllView,
    AgreementUpdateView
)

urlpatterns = [
    url(r'^create/$', AgreementCreateView.as_view(), name='create'),
    url(r'^all/$', AgreementListAllView.as_view(), name='list-all'),
    url(r'^(?P<nr>[\w-]+)/$', AgreementDetailView.as_view(), name='detail'),
    url(r'^(?P<nr>[\w-]+)/edit/$', AgreementUpdateView.as_view(), name='edit'),
    url(r'$', AgreementListView.as_view(), name='list')
] 

crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth.views import (
    LoginView, 
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.core.urlresolvers import reverse_lazy

from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', LoginView.as_view(template_name='user/login.html', redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
     url(r'^password_reset/done/$',
        PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^reset/done/$',
        PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
    url(r'^clients/', include('clients.urls', namespace='clients')), 
    url(r'^products/', include('products.urls', namespace='products')), 
    url(r'^agreements/', include('agreements.urls', namespace='agreements')), 
    url(r'^transactions/', include('transactions.urls', namespace='transactions')),
    url(r'^commisions/', include('commisions.urls', namespace='commisions')),
    url(r'^employees/', include('employees.urls', namespace='employees')),  
    url(r'^events/', include('events.urls', namespace='events')),  
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),  
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),  
    url(r'^$', login_required(TemplateView.as_view(template_name='index.html')), name='about'),
]

agreements/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

User = settings.AUTH_USER_MODEL


class Agreement(models.Model):
    
    ACTIVE = 'A'
    UNACTIVE = 'U'
    TAG_CHOICES = (
        (ACTIVE, 'Aktywny'),
        (UNACTIVE, 'Nieaktywny')
    )
    
    client_id = models.ForeignKey('clients.Client')
    owner = models.ForeignKey(User)
    buyer = models.ForeignKey(User, related_name="buyer")
    valid_since = models.DateField(auto_now=False, auto_now_add=False)
    valid_to = models.DateField(auto_now=False, auto_now_add=False)
    nr = models.CharField(max_length=20)
    state = models.CharField(max_length=1, choices=TAG_CHOICES, default=ACTIVE)
    amount = models.DecimalField(max_digits=17, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('agreements:detail', kwargs={'nr': self.nr})

    def __str__(self):
        return str(self.id) + ' ' + str(self.client_id)

class Declaration(models.Model):
    client_id = models.ForeignKey('clients.Client')
    product_id = models.ForeignKey('products.Product')
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id) + ' ' + str(self.client_id)

agreements/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from django.forms.models import inlineformset_factory
from .models import Agreement, Declaration

class AgreementCreateForm(forms.ModelForm):
    valid_since = forms.DateField(widget=forms.DateInput(format = '%Y-%m-%d'), input_formats=('%Y-%m-%d',))
    class Meta:
        model = Agreement
        exclude = ('owner', 'valid_to')
    def clean_nr(self):
        nr = self.cleaned_data.get('nr', False)
        if nr.find('/')!=-1 or nr.find("\'")!=-1:
            raise forms.ValidationError('Numer umowy nie jest prawidłowy')
        return self.cleaned_data["nr"] 
        
class DeclarationCreateForm(forms.ModelForm):
    class Meta:
        model = Declaration
        fields = ['product_id']

agreements/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,get_object_or_404, reverse
from django.http import Http404
from django.db import transaction
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from dateutil.relativedelta import relativedelta
from django.core.exceptions import PermissionDenied

from multi_form_view import MultiModelFormView

from .models import Agreement, Declaration
from .forms import AgreementCreateForm, DeclarationCreateForm

class AgreementListView(LoginRequiredMixin, ListView):
    def get_queryset(self, *args, **kwargs):
        qs = Agreement.objects.filter(owner=self.request.user)
        return qs

class AgreementListAllView(LoginRequiredMixin, ListView):
    def get_queryset(self, *args, **kwargs):
        qs = Agreement.objects.all()
        return qs

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data(object_list=self.object_list)
        if self.request.user.employee.role is 'A':
            return self.render_to_response(context)
        else:
            raise PermissionDenied

class AgreementDetailView(LoginRequiredMixin, DetailView):

    def get_object(self):
        nr = self.kwargs.get('nr')
        if nr is None:
            raise Http404
        if self.request.user.employee.role == 'E':
            return get_object_or_404(Agreement, nr__iexact=nr, owner=self.request.user)
        return get_object_or_404(Agreement, nr__iexact=nr)

    def get_context_data(self, *args, **kwargs):
        context = super(AgreementDetailView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Umowa nr'
        id = self.get_object().id
        if id is None:
            raise Http404
        context['declaration'] = Declaration.objects.get(id=id)
        return context

class AgreementCreateView(LoginRequiredMixin, MultiModelFormView, CreateView):
    form_classes = {
        'agreement_form' : AgreementCreateForm,
        'declaration_form' : DeclarationCreateForm,
    }
    nr = None
    template_name = 'agreements/agreement_form.html'

    def get_success_url(self):
        return reverse('agreements:detail', kwargs={'nr': self.nr})
    
    def get_context_data(self, *args, **kwargs):
        context = super(AgreementCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Dodaj umowę'
        return context

    def forms_valid(self, forms):
        with transaction.atomic():
            agreement = forms['agreement_form'].save(commit=False)
            self.nr = agreement.nr 
            agreement.owner = self.request.user 
            declaration = forms['declaration_form'].save(commit=False)
            agreement.valid_to = agreement.valid_since + relativedelta(years=declaration.product_id.parameter.duration)
            declaration.client_id = agreement.client_id
            declaration.save()
            agreement.save()
        return super(AgreementCreateView, self).forms_valid(forms)


class AgreementUpdateView(LoginRequiredMixin, MultiModelFormView, UpdateView):
    form_classes = {
        'agreement_form' : AgreementCreateForm,
        'declaration_form' : DeclarationCreateForm,
    }
    nr = None
    template_name = 'agreements/agreement_form.html'

    def get_objects(self):
        self.nr = self.kwargs.get('nr', None)
        try:
            agreement = Agreement.objects.get(nr=self.nr)
            print(agreement.id)
        except Agreement.DoesNotExist:
            agreement = None
        return {
            'agreement_form': agreement,
            'declaration_form': Declaration.objects.get(id=agreement.id)
        }

    def get_context_data(self, *args, **kwargs):
        context = super(AgreementUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Edytuj umowę'
        return context

    def get_success_url(self):
        return reverse('agreements:detail', kwargs={'nr': self.nr})

    def forms_valid(self, forms):
        with transaction.atomic():
            agreement = forms['agreement_form'].save()
            self.nr = agreement.nr 
            agreement.save()
            declaration = forms['declaration_form'].save(commit=False)
            agreement.valid_to = agreement.valid_since + relativedelta(years=declaration.product_id.parameter.duration)
            declaration.client_id = agreement.client_id
            declaration.save()
            agreement.save()
        
        return super(AgreementUpdateView, self).forms_valid(forms)

agreements/templates/agreements/agreement_detail.html
{% extends "base_site.html" %}

{% block title %} Project Details {% endblock title %}

{% block sidebar_class %}menu_fixed{% endblock sidebar_class %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>{{title}} {{agreement.nr}}</h3>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_title">
              <h2><a href="{% url 'clients:detail' agreement.client_id.slug %}">{{agreement.client_id.name}} {{agreement.client_id.surname}}</a></h2>
              <div class="clearfix"></div>
            </div>

            <div class="x_content">

                <div class="col-md-12 col-sm-12 col-xs-12">

                    <ul class="stats-overview">
                    <li>
                        <span class="name"> Kwota umowy </span>
                        <span class="value text-success"> {{agreement.amount}} zł</span>
                    </li>
                    <li>
                        <span class="name"> Ważna od </span>
                        <span class="value text-success"> {{agreement.valid_since}} </span>
                    </li>
                    <li>
                        <span class="name"> Ważna do </span>
                        <span class="value text-success"> {{agreement.valid_to}} </span>
                    </li>
                    </ul>
                    <br />
                </div>


            </div>

              <!-- start project-detail sidebar -->
              <div class="col-md-12 col-sm-12 col-xs-12">

                <section class="panel">

                  <div class="panel-body">
                    <h3 class="green"><i class="fa fa-file-text"></i> {{declaration.product_id.name}}</h3>

                    <p>{{declaration.product_id.product_type.description}}</p>
                    <br />

                    <div class="project_detail">
                      <p class="title">Klient</p>
                      <p><a href="{% url 'clients:detail' agreement.client_id.slug %}"><small style="color:#fff; padding:3px 6px; background: #73879C">{{agreement.client_id.client_id}}</small></a></p>

                      <p class="title">Utworzona przez</p>
                      <p><small style="color:#fff; padding:3px 6px; background: #73879C">{{agreement.owner.employee.name }} {{agreement.owner.employee.surname}}</small></p>

                      <p class="title">Sprzedawca</p>
                      <p><small style="color:#fff; padding:3px 6px; background: #73879C">{{agreement.buyer.employee.name }} {{agreement.buyer.employee.surname}}</small></p>

                      <p class="title">Inne umowy dla {{agreement.client_id.client_id}}</p>

                      <p>
                        {% for agr in agreement.client_id.agreement_set.all %}
                            <a href="{% url 'agreements:detail' agr.nr %}"><small style="color:#fff; padding:3px 6px; background: #5cb85c">{{agr.nr}}</small></a>
                        {%endfor%}

                      </p>
                    </div>

                    <br />

                    <div class="mtop20">
                        <a class="btn btn-success" href="{% url 'agreements:edit' agreement.nr %}"><i class="fa fa-edit m-right-xs"></i> Edytuj</a>
                        <a class="btn btn-default" href="{% url 'agreements:list' %}"><i class="fa fa-list m-right-xs"></i> Lista umów</a>
                    </div>

                    
                  </div>

                </section>

              </div>
              <!-- end project-detail sidebar -->

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- ECharts -->
  <script src="/static/vendors/echarts/dist/echarts.min.js"></script>
{% endblock javascripts %}

agreements/templates/agreements/agreement_form.html
{% extends "base_site.html" %} {% block title %} {{title}} {% endblock title %} 

{% block stylesheets %}
  {{ block.super }}
    <link href="/static/vendors/pnotify/dist/pnotify.css" rel="stylesheet">
    <link href="/static/vendors/pnotify/dist/pnotify.buttons.css" rel="stylesheet">
    <link href="/static/vendors/pnotify/dist/pnotify.nonblock.css" rel="stylesheet">
{% endblock stylesheets %} 

{% block content %}
{% load myfilters %}

<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>{{title}}</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel form_wizard wizard_horizontal">
                    <div class="x_content">                        
                        <form action="." method="post" id="demo-form2" class="form-horizontal form-label-left">{% csrf_token %}
                            <div class="form-group">
                                {{ forms.agreement_form.client_id.errors }}
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{ forms.agreement_form.client_id.id_for_label }}">Klient
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{forms.agreement_form.client_id|add_attributes:'class: form-control col-md-7 col-xs-12, required:required'}}
                                    {{forms.agreement_form.client_id.id}}
                                    
                                </div>
                            </div>

                            <div class="form-group">
                                {{ forms.agreement_form.buyer.errors }}
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{ forms.agreement_form.buyer.id_for_label }}">Sprzedawca
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{forms.agreement_form.buyer|add_attributes:'class: form-control col-md-7 col-xs-12, required:required'}}
                                    {{forms.agreement_form.buyer.id}}
                                    
                                </div>
                            </div>

                            <div class="form-group">
                                {{ forms.declaration_form.product_id.errors }}
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{ forms.declaration_form.product_id.id_for_label }}">Produkt
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{forms.declaration_form.product_id|add_attributes:'class: form-control col-md-7 col-xs-12, required:required'}}
                                    {{forms.declaration_form.product_id.id}}
                                </div>
                            </div>

                            <div class="form-group">
                                {{ forms.agreement_form.valid_since.errors }}
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{ forms.agreement_form.valid_since.id_for_label }}">Ważna od 
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{forms.agreement_form.valid_since|add_attributes:'class:date-input form-control col-md-7 col-xs-12 valid-date, required:required'}}
                                    {{forms.agreement_form.valid_since.id}}
                                    <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                {{ forms.agreement_form.nr.errors }}
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{ forms.agreement_form.nr.id_for_label }}">Numer umowy
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{forms.agreement_form.nr|add_attributes:'class: form-control col-md-7 col-xs-12, required:required'}}
                                    {{forms.agreement_form.nr.id}}
                                    <p>Numer umowy powinien zachować wzór <i>01_234_56B</i> i/ub nie może zawierać znaków "/" oraz "\"</p>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Status</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div id="agreement_state" class="btn-group" data-toggle="buttons">
                                        {% for choice in forms.agreement_form.state.field.choices %}
                                        <label class="btn btn-default {% if forms.agreement_form.state.value == choice.0 %} active {% endif %}" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default" for='{{ forms.agreement_form.state.auto_id }}_{{ forloop.counter0 }}'>
                                            <input name='{{ forms.agreement_form.state.name }}' 
                                            id='{{ forms.agreement_form.state.auto_id }}_{{ forloop.counter0 }}' type='radio' value='{{ choice.0 }}'
                                            {% if forms.agreement_form.state.value == choice.0 %} checked='checked' {% endif %} required
                                            /> {{ choice.1 }}
                                        </label>
                                        {% endfor %}
                                        <br><br>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                {{ forms.agreement_form.amount.errors }}
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{ forms.agreement_form.amount.id_for_label }}">Kwota
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    {{forms.agreement_form.amount|add_attributes:'class: form-control col-md-7 col-xs-12, required:required'}}
                                    {{forms.agreement_form.amount.id}}
                                </div>
                            </div>

                            
                        
                            

                            <div class="ln_solid"></div>

                           
                            <div class="form-group text-center">
                                <button type="reset" class="btn btn-primary">Reset</button>
                                <button type="submit" class="btn btn-success">Zapisz</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %} {% block javascripts %} 
{{ block.super}}
<script src="/static/vendors/datetimepicker/jquery.datetimepicker.full.min.js"></script>
<script src="/static/vendors/pnotify/dist/pnotify.js"></script>
<script src="/static/vendors/pnotify/dist/pnotify.nonblock.js"></script>

<script>
(function () {
	$(document).ready(function() {
		$(".valid-date").datetimepicker({    
            timepicker:false,
            format:'Y-m-d',
        });
	});
})(jQuery);

(function () {
    if($('.errorlist').length){
        $('.errorlist').hide();
        $('.errorlist').each(function(){
            console.log(this);
            new PNotify({
                title: "Ostrzeżenie",
                text: $(this).find('li').text(),
                type: 'danger',
                styling: 'bootstrap3'
            });
        })
    }
})(jQuery);
</script>
{% endblock javascripts %}

agreements/templates/agreements/agreement_list.html
{% extends "base_site.html" %}
{% load myfilters %}

{% block title %} Table Dynamic {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Umowy</h3>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel"><br>
                <a href="{% url 'agreements:create' %}" class="btn btn-primary" role="button"><i class="fa fa-plus-square-o" aria-hidden="true"></i> Dodaj umowę</a><br><br>
 
              <div class="x_content">
                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                  <thead>
                    <tr>
                      <th>Numer umowy</th>
                      <th>Imię</th>
                      <th>Nazwisko</th>
                      <th>Kwota</th>
                      <th>Ważna od</th>
                      <th>Ważna do</th>
                      <th>Status</th>
                      <th>Data utworzenia</th>
                      <th>Uwtorzona przez</th>
                      <th></th>
                    </tr>
                  </thead>

                  <tbody>
                    {% for agreement in object_list %}
                    <tr>
                      <td>{{agreement.nr}}</td>
                      <td>{{agreement.client_id.name}}</td>
                      <td>{{agreement.client_id.surname}}</td>
                      <td>{{agreement.amount}}</td>
                      <td>{{agreement.valid_since}}</td>
                      <td>{{agreement.valid_to}}</td>
                      <td>{{agreement.state|state}}</td>
                      <td>{{agreement.timestamp}}</td>
                      <td>{{agreement.owner.employee.name}} {{agreement.owner.employee.surname}}</td>
                      <td ><a style="font-size: 0.8em;" href="{{ agreement.get_absolute_url }}" class="btn btn-info" role="button"><i class="fa fa-search" aria-hidden="true"></i></a></td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
      
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- Datatables -->
  <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
  <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
  <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
  <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>

{% endblock javascripts %}